version: '3'

services:
  ui:
    build:
      context: ui
      args:
        - VITE_SENTRY_DSN=${SENTRY_DSN}
        - VITE_SENTRY_RELEASE=${APP_NAME}@${APP_VERSION}
        # sentry environment is computed automatically
    ports:
      - "${SANDLE_DEMO_PORT:-80}:80"
    depends_on:
      - auth-wrapper
    restart: unless-stopped

  auth-wrapper:
    build:
      context: auth-wrapper
      args:
        - SENTRY_DSN
        - SENTRY_RELEASE=${APP_NAME}@${APP_VERSION}
    environment:
      - AUTH_TOKEN
      - LOG_LEVEL
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-development}
    depends_on:
      - vllm
    restart: unless-stopped

  vllm:
    build:
      context: vllm
      args:
        - SENTRY_DSN
        - SENTRY_RELEASE=${APP_NAME}@${APP_VERSION}
    environment:
      - AUTH_TOKEN
      - VLLM_MODEL
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-development}
    restart: unless-stopped
