version: '3'

services:
  demo:
    build: demo
    ports:
      - "${OPENAISLE_DEMO_PORT:-80}:80"
    depends_on:
      - openai-wrapper
    restart: unless-stopped

  openai-wrapper:
    build: openai-wrapper
    command:
      - http://opt:8000/v1/completions
      - --port
      - '8000'
    depends_on:
      - opt
    environment:
      - OPENAISLE_AUTH_TOKEN
    restart: unless-stopped

  opt:
    build: opt
    command:
      - --port
      - '8000'
      - --num-gpus
      - '8'
      - --first-gpu-memory
      - '12GB'
      - --successive-gpu-memory
      - '24GB'
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - huggingface-models:/root/.cache/huggingface

volumes:
  huggingface-models:
