# Root docker-compose configuration.  Includes demo (UI) and OpenAI wrapper but no backends.
# Intended to be used in tandem with one or more backend configuration files.  Example:
#
#   docker-compose -f docker-compose.yml -f docker-compose.backend-stub.yml

version: '3'

services:
  demo:
    build:
      context: demo
      args:
        - VITE_SENTRY_DSN=${SENTRY_DSN}
        - VITE_SENTRY_RELEASE=${APP_NAME}@${APP_VERSION}
        # sentry environment is computed automatically
    ports:
      - "${SANDLE_DEMO_PORT:-80}:80"
    depends_on:
      - openai-wrapper
    restart: unless-stopped

  openai-wrapper:
    build:
      context: openai-wrapper
      args:
        - SENTRY_DSN
        - SENTRY_RELEASE=${APP_NAME}@${APP_VERSION}
    command:
      - --port
      - '8000'
      - -l
      - DEBUG
    ## Specify API keys in authorized-users.txt file: part 1/2
    #  - --auth-token-is-user
    #  - --auth-token-file
    #  - /opt/sandle/authorized-users.txt
    environment:
      - SANDLE_AUTH_TOKEN
      - SANDLE_SINGLE_MODEL
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-development}
    restart: unless-stopped
    ## Specify API keys in authorized-users.txt file: part 2/2
    #volumes:
    #  - type: bind
    #    source: ./authorized-users.txt
    #    target: /opt/sandle/authorized-users.txt
    #    read_only: true
