# Stub backend docker-compose configuration for use during development and testing.
# Intended to be used in tandem with the root configuration file.  Example:
#
#   docker-compose -f docker-compose.yml -f docker-compose.backend-stub.yml

version: '3'

services:
  openai-wrapper:
    environment:
      - SANDLE_BACKEND_STUB=http://backend-stub:8000
    depends_on:
      - backend-stub

  backend-stub:
    build:
      context: backend-stub
    environment:
      - SANDLE_LOG_LEVEL
    restart: unless-stopped
