version: '3'

services:
  demo:
    build: demo
    ports:
      - "${OPENAISLE_DEMO_PORT:-80}:80"
    depends_on:
      - openai-adapter
    restart: unless-stopped

  openai-adapter:
    build: openai-adapter
    command:
      - http://opt:8000/v1/completions
      - --port
      - '8000'
      - --allow-model
      - facebook/opt-66b
    depends_on:
      - opt
    restart: unless-stopped

  opt:
    build: opt
    command:
      - --port
      - '8000'
      - --preload-model
      - facebook/opt-66b
      - --num-gpus
      - '8'
      - --first-gpu-memory
      - '12GB'
      - --successive-gpu-memory
      - '24GB'
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    volumes:
      - huggingface-models:/root/.cache/huggingface

volumes:
  huggingface-models:
