# DeepSpeed backend docker-compose configuration.
# Creates a volume to retain cached extension files across runs.
# Intended to be used in tandem with the root configuration file.  Example:
#
#   docker-compose -f docker-compose.yml -f docker-compose.backend-deepspeed.yml

version: '3.7'

services:
  openai-wrapper:
    environment:
      - SANDLE_BACKEND_DEEPSPEED=http://backend-deepspeed:8000
    depends_on:
      - backend-deepspeed

  backend-deepspeed:
    build:
      context: backend-deepspeed
      args:
        - SENTRY_DSN
        - SENTRY_RELEASE=${APP_NAME}@${APP_VERSION}
    environment:
      - SANDLE_MODEL_ID=${SANDLE_DEEPSPEED_MODEL:-bigscience/bloom-560m}
      - SANDLE_MODEL_PATH=/root/.cache/mii_models
      - SANDLE_LOG_LEVEL
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-development}
    init: true
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - deepspeed-cache:/root/.cache

volumes:
  deepspeed-cache:
