compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
fsdp_config: {}
machine_rank: 0
main_process_ip: 172.23.93.102
main_process_port: 12333
main_training_function: main
mixed_precision: 'no'
num_machines: 3
num_processes: 8
use_cpu: false
